modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="misticita"
version="1.0.0"
displayName="Misticita Mod"
authors="Serggi.c, duustixx"
description='''
Un mod que a√±ade Misticita, un nuevo material poderoso.
Incluye herramientas, armadura y bloques.
'''

[[dependencies.misticita]]
modId="forge"
versionRange="[47.0.0,)"
mandatory=true
ordering="NONE"
side="BOTH"

[[dependencies.misticita]]
modId="minecraft"
versionRange="[1.20.1,1.21)"
mandatory=true
ordering="NONE"
side="BOTH"
